#! /usr/bin/python

import os
import sys
import json
import subprocess

project_name = os.path.basename(os.getcwd())

data_dir = __file__ + ".data"
print(data_dir)
pods_json_dir = os.path.join(os.path.sep, data_dir, "pods.json")


pods = json.load(open(pods_json_dir))

pods_string = ""
for pod, version in pods.iteritems():
    pods_string += "  pod '" + pod + "'"
    if version != None:
        pods_string += ", '~> " + str(version) + "'"
    pods_string += "\n"


pod_file_content = """platform :ios, '10.0'
target '{0}' do
  use_frameworks!
{1}
end
""".format(project_name, pods_string)


fo = open("Podfile", "wb")
fo.write(pod_file_content)
fo.close()

print subprocess.Popen("pod install", shell=True, stdout=subprocess.PIPE).stdout.read()
