#!/usr/bin/env python

import glob, os
import subprocess

import os
for file in os.listdir(os.getcwd()):
    if file.endswith(".xcworkspace"):
        command = "open " + file
        print subprocess.Popen(command, shell=True, stdout=subprocess.PIPE).stdout.read()
